// Code generated by "stringer -type ErrCode -linecomment"; DO NOT EDIT.

package error_code

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServerError-10101]
	_ = x[TooManyRequests-10102]
	_ = x[ParamBindError-10103]
	_ = x[AuthorizationError-10104]
	_ = x[CallHTTPError-10105]
	_ = x[ResubmitError-10106]
	_ = x[ResubmitMsg-10107]
	_ = x[IllegalUserName-20101]
	_ = x[UserCreateError-20102]
	_ = x[UserUpdateError-20103]
	_ = x[UserSearchError-20104]
	_ = x[ConfigEmailError-20401]
	_ = x[ConfigRedisConnectError-20403]
	_ = x[ConfigMySQLConnectError-20404]
	_ = x[ConfigMySQLInstallError-20405]
	_ = x[ConfigMySQLSelectError-20406]
	_ = x[SearchRedisError-20501]
	_ = x[ClearRedisError-20502]
	_ = x[SearchRedisEmpty-20503]
	_ = x[SearchMySQLError-20504]
	_ = x[BookNotFoundError-20701]
	_ = x[BookHasBeenBorrowedError-20702]
}

const (
	_ErrCode_name_0 = "Internal Server ErrorToo Many Requests参数信息有误签名信息有误调用第三方HTTP接口失败ResubmitError请勿重复提交"
	_ErrCode_name_1 = "非法用户名创建用户失败更新用户失败查询用户失败"
	_ErrCode_name_2 = "修改邮箱配置失败"
	_ErrCode_name_3 = "Redis连接失败MySQL连接失败MySQL初始化数据失败MySQL查询失败"
	_ErrCode_name_4 = "查询RedisKey失败清空RedisKey失败查询的RedisKey不存在查询mysql失败"
	_ErrCode_name_5 = "书未找到书已经被借走了"
)

var (
	_ErrCode_index_0 = [...]uint8{0, 21, 38, 56, 74, 105, 118, 136}
	_ErrCode_index_1 = [...]uint8{0, 15, 33, 51, 69}
	_ErrCode_index_3 = [...]uint8{0, 17, 34, 60, 77}
	_ErrCode_index_4 = [...]uint8{0, 20, 40, 66, 83}
	_ErrCode_index_5 = [...]uint8{0, 12, 33}
)

func (i ErrCode) String() string {
	switch {
	case 10101 <= i && i <= 10107:
		i -= 10101
		return _ErrCode_name_0[_ErrCode_index_0[i]:_ErrCode_index_0[i+1]]
	case 20101 <= i && i <= 20104:
		i -= 20101
		return _ErrCode_name_1[_ErrCode_index_1[i]:_ErrCode_index_1[i+1]]
	case i == 20401:
		return _ErrCode_name_2
	case 20403 <= i && i <= 20406:
		i -= 20403
		return _ErrCode_name_3[_ErrCode_index_3[i]:_ErrCode_index_3[i+1]]
	case 20501 <= i && i <= 20504:
		i -= 20501
		return _ErrCode_name_4[_ErrCode_index_4[i]:_ErrCode_index_4[i+1]]
	case 20701 <= i && i <= 20702:
		i -= 20701
		return _ErrCode_name_5[_ErrCode_index_5[i]:_ErrCode_index_5[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
